spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 687098864824-1tbt0lbp8e9bhc83blu1525mmkksvbcp.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: 3069adea2f31327cf91478ab2b91dbab
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: 69i2oXfZ4aEeSwHGnabl
            client-secret: QvExBfS7tv
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
              - profile_image 