spring:
  datasource:
    url: "jdbc:sqlite::memory:"
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "testSecretKey1234567890123456789012345678901234567890"
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 604800
  oauth2:
    redirect-uri: "http://localhost:8080/oauth2/callback" 